# Generated by Django 5.0.2 on 2024-10-14 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppIoT", "0002_room_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descrizione", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Utente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cognome", models.CharField(max_length=255)),
                ("nascita", models.DateField()),
                ("carta_di_pagamento", models.CharField(max_length=16)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("studente", "Studente"),
                            ("relatore", "Relatore di Conferenze"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venditore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("pubblica", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name="aula",
            options={},
        ),
        migrations.RemoveField(
            model_name="aula",
            name="punteggio",
        ),
        migrations.AddField(
            model_name="aula",
            name="occupato",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aula",
            name="posizione",
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name="aula",
            name="prezzo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="sensori_arduino",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="aula",
            name="bridge",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppIoT.bridge",
            ),
        ),
        migrations.CreateModel(
            name="Calendario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evento", models.CharField(max_length=255)),
                ("data_evento", models.DateTimeField()),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AppIoT.utente"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bridge",
            name="venditore",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="AppIoT.venditore"
            ),
        ),
    ]
