# Generated by Django 5.0.2 on 2024-10-14 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppIoT", "0003_bridge_utente_venditore_alter_aula_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Aula",
        ),
    ]
