# Generated by Django 5.0.2 on 2024-10-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppIoT", "0004_delete_aula"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="posizione",
            field=models.CharField(default=True, max_length=255),
        ),
    ]
