# Generated by Django 5.0.2 on 2024-10-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppIoT", "0005_room_posizione"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DatiSeriale",
        ),
        migrations.DeleteModel(
            name="MainPage",
        ),
        migrations.DeleteModel(
            name="MyModel",
        ),
        migrations.DeleteModel(
            name="SaveData",
        ),
        migrations.RemoveField(
            model_name="room",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="room",
            name="posizione",
        ),
        migrations.RemoveField(
            model_name="room",
            name="price",
        ),
        migrations.RemoveField(
            model_name="room",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="room",
            name="sensor_data",
        ),
        migrations.AddField(
            model_name="room",
            name="co2",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="humidity",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="latitudine",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="light",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="longitudine",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="occupancy",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="people",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="probability",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="room_size",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="sound",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="temperature",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
