# Generated by Django 5.0.2 on 2024-10-18 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppIoT", "0006_delete_datiseriale_delete_mainpage_delete_mymodel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="occupancy",
            new_name="bestroom",
        ),
    ]
