# Generated by Django 5.0.2 on 2024-10-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppIoT", "0007_rename_occupancy_room_bestroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
