# Generated by Django 5.0.2 on 2024-10-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppIoT", "0008_room_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="type",
            field=models.CharField(default=True, max_length=100),
        ),
    ]
