# Generated by Django 5.0.2 on 2024-10-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppIoT", "0009_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(default="studio", max_length=100),
        ),
    ]
