# Generated by Django 5.0.2 on 2024-11-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppIoT", "0010_alter_room_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="bridge",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
