# Generated by Django 5.0.2 on 2025-03-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIoT', '0011_room_bridge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='utente',
        ),
        migrations.RemoveField(
            model_name='bridge',
            name='venditore',
        ),
        migrations.AddField(
            model_name='room',
            name='adjacent_rooms',
            field=models.ManyToManyField(blank=True, to='AppIoT.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_transferred', models.TextField()),
                ('room_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_from', to='AppIoT.room')),
                ('room_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_to', to='AppIoT.room')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Calendario',
        ),
        migrations.DeleteModel(
            name='Utente',
        ),
    ]
