# Generated by Django 5.0.2 on 2025-03-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIoT', '0012_remove_calendario_utente_remove_bridge_venditore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bridge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
