# Generated by Django 5.0.2 on 2025-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIoT', '0013_alter_room_bridge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(default='generico', max_length=100),
        ),
    ]
