# Generated by Django 5.0.2 on 2025-03-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIoT', '0015_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='adafruit_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='InteractionLog',
        ),
    ]
