# Generated by Django 5.0.2 on 2025-03-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIoT', '0016_room_adafruit_position_delete_interactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
