# Generated by Django 5.0.2 on 2025-03-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppIoT', '0017_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='latitude',
            new_name='latitudine',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='longitude',
            new_name='longitudine',
        ),
    ]
