# Generated by Django 5.0.2 on 2025-03-31 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIoT', '0019_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('luogo', models.CharField(blank=True, max_length=255, null=True)),
                ('inizio', models.DateTimeField()),
                ('fine', models.DateTimeField()),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='AppIoT.user')),
            ],
        ),
    ]
