# Generated by Django 5.0.2 on 2025-03-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIoT', '0020_userevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_co2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='last_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='last_light',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='last_sound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='last_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='latitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='longitudine',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
