# Generated by Django 5.0.2 on 2025-04-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIoT', '0021_room_last_co2_room_last_humidity_room_last_light_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_score_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
