# Generated by Django 5.0.2 on 2025-04-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIoT', '0023_room_last_prediction_time_predictionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('co2', models.FloatField()),
                ('light', models.FloatField()),
                ('sound', models.FloatField()),
                ('people', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_history', to='AppIoT.room')),
            ],
        ),
    ]
