# Generated by Django 5.0.2 on 2025-04-04 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIoT', '0024_sensorhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField()),
                ('commento', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='AppIoT.room')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppIoT.user')),
            ],
        ),
    ]
