# Generated by Django 5.0.2 on 2025-04-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIoT', '0025_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
